cShareSystems.load_pas("Lilly", [
    "coui://ui/mods/lilly/systems/lilly_all8.pas",           
    "coui://ui/mods/lilly/systems/lilly_debw.pas",           
    "coui://ui/mods/lilly/systems/lilly_erbw.pas",           
    "coui://ui/mods/lilly/systems/lilly_ersp.pas",           
    "coui://ui/mods/lilly/systems/lilly_ersw4.pas",          
    "coui://ui/mods/lilly/systems/lilly_ersw8.pas",          
    "coui://ui/mods/lilly/systems/lilly_icsw.pas",           
    "coui://ui/mods/lilly/systems/lilly_icwb c.pas",         
    "coui://ui/mods/lilly/systems/lilly_mnbw.pas",           
    "coui://ui/mods/lilly/systems/lilly_mt-sp2.pas",         
    "coui://ui/mods/lilly/systems/lilly_mt_sp.pas",          
    "coui://ui/mods/lilly/systems/lilly_mtbw.pas",           
    "coui://ui/mods/lilly/systems/lilly_trbw v2.pas",        
    "coui://ui/mods/lilly/systems/lilly_trbw.pas",           
]);                                                          
