{
    "name": "lilly erSW8",
    "description": "",
    "creator": "",
    "version": "",
    "planets": [
        {
            "name": "RW-n0-p31",
            "mass": 10000,
            "position_x": 12625,
            "position_y": 0,
            "velocity_x": -0.00000869889208843233,
            "velocity_y": 199.0074462890625,
            "required_thrust_to_move": 9,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 185858928,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "RW-n0-p31",
            "mass": 10000,
            "position_x": 0,
            "position_y": 12625,
            "velocity_x": -199.0074462890625,
            "velocity_y": -0.00000869889208843233,
            "required_thrust_to_move": 9,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 185858928,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "RW-n0-p31",
            "mass": 10000,
            "position_x": -12625,
            "position_y": 0,
            "velocity_x": 0.00000869889208843233,
            "velocity_y": -199.0074462890625,
            "required_thrust_to_move": 9,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 185858928,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "RW-n0-p31",
            "mass": 10000,
            "position_x": 0,
            "position_y": -12624.9990234375,
            "velocity_x": 199.0074462890625,
            "velocity_y": 0.00000869889208843233,
            "required_thrust_to_move": 9,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 185858928,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "RW-n0-p31",
            "mass": 10000,
            "position_x": 8927.2236328125,
            "position_y": 8927.2236328125,
            "velocity_x": -140.71949768066406,
            "velocity_y": 140.71949768066406,
            "required_thrust_to_move": 9,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 185858928,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "RW-n0-p31",
            "mass": 10000,
            "position_x": 8927.2236328125,
            "position_y": -8927.2236328125,
            "velocity_x": 140.71949768066406,
            "velocity_y": 140.71949768066406,
            "required_thrust_to_move": 9,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 185858928,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "RW-n0-p31",
            "mass": 10000,
            "position_x": -8927.2236328125,
            "position_y": 8927.2236328125,
            "velocity_x": -140.71949768066406,
            "velocity_y": -140.71949768066406,
            "required_thrust_to_move": 9,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 185858928,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "RW-n0-p31",
            "mass": 10000,
            "position_x": -8927.2236328125,
            "position_y": -8927.2236328125,
            "velocity_x": 140.71949768066406,
            "velocity_y": -140.71949768066406,
            "required_thrust_to_move": 9,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 185858928,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": true,
                "symmetricalStarts": true,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        }
    ]
}