{
    "name": "Gamma System",
    "description": "",
    "creator": "",
    "version": "",
    "planets": [
        {
            "name": "Trizz",
            "mass": 50000,
            "position_x": 114999.9921875,
            "position_y": -0.015625,
            "velocity_x": 42.00001525878906,
            "velocity_y": 39.99959945678711,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1319488640,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Minogue",
            "mass": 5000,
            "position_x": 117399.9921875,
            "position_y": -0.012401587329804897,
            "velocity_x": 42.00046157836914,
            "velocity_y": -282.7490234375,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 402621504,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 10,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 50,
                "heightAdjustments": []
            }
        },
        {
            "name": "Minogue",
            "mass": 5000,
            "position_x": 114999.9921875,
            "position_y": -2400.011962890625,
            "velocity_x": -280.748779296875,
            "velocity_y": 39.99958419799805,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 402621504,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 50,
                "heightAdjustments": []
            }
        },
        {
            "name": "Minogue",
            "mass": 5000,
            "position_x": 112599.9921875,
            "position_y": -0.01161956787109375,
            "velocity_x": 42.00054168701172,
            "velocity_y": 362.74822998046875,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 402621504,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 50,
                "heightAdjustments": []
            }
        },
        {
            "name": "Minogue",
            "mass": 5000,
            "position_x": 114999.9921875,
            "position_y": 2399.988037109375,
            "velocity_x": 364.74835205078125,
            "velocity_y": 39.99961471557617,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 402621504,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 50,
                "heightAdjustments": []
            }
        },
        {
            "name": "Minogue",
            "mass": 5000,
            "position_x": 118099.9921875,
            "position_y": -0.012200523167848587,
            "velocity_x": 42.00033950805664,
            "velocity_y": -243.9813232421875,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 402621504,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 50,
                "heightAdjustments": []
            }
        },
        {
            "name": "Minogue",
            "mass": 5000,
            "position_x": 114999.9921875,
            "position_y": -3100.011962890625,
            "velocity_x": -241.98106384277344,
            "velocity_y": 39.99958801269531,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 402621504,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 50,
                "heightAdjustments": []
            }
        },
        {
            "name": "Minogue",
            "mass": 5000,
            "position_x": 111899.9921875,
            "position_y": -0.011929512023925781,
            "velocity_x": 42.00033950805664,
            "velocity_y": 323.98052978515625,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 402621504,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 50,
                "heightAdjustments": []
            }
        },
        {
            "name": "Minogue",
            "mass": 5000,
            "position_x": 115000,
            "position_y": 3100,
            "velocity_x": 325.980224609375,
            "velocity_y": 39.998897552490234,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 402621504,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 50,
                "heightAdjustments": []
            }
        }
    ]
}