{
    "name": "lilly erSW4",
    "description": "",
    "creator": "",
    "version": "",
    "planets": [
        {
            "name": "Uzgull SW",
            "mass": 50000,
            "position_x": 12625,
            "position_y": 0,
            "velocity_x": -0.00000869889208843233,
            "velocity_y": 199.0074462890625,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 335407200,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 10,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "Uzgull SW",
            "mass": 50000,
            "position_x": 0,
            "position_y": -12625,
            "velocity_x": 199.0074462890625,
            "velocity_y": 0.00000869889208843233,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 335407200,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "Uzgull SW",
            "mass": 50000,
            "position_x": 0,
            "position_y": 12625,
            "velocity_x": -199.0074462890625,
            "velocity_y": -0.00000869889208843233,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 335407200,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "Uzgull SW",
            "mass": 50000,
            "position_x": -12625,
            "position_y": 0,
            "velocity_x": 0.00000869889208843233,
            "velocity_y": -199.0074462890625,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 335407200,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        }
    ]
}