{
    "name": "Lilly ErBW+S4",
    "description": "",
    "creator": "",
    "version": "",
    "planets": [
        {
            "name": "Seigaldonia BW",
            "mass": 50000,
            "position_x": 12616.955078125,
            "position_y": 450.60552978515625,
            "velocity_x": -7.102889060974121,
            "velocity_y": 198.8806610107422,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 785632832,
                "radius": 1300,
                "heightRange": 100,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 5,
                "landingZoneSize": 500,
                "heightAdjustments": []
            }
        },
        {
            "name": "O-01",
            "mass": 5000,
            "position_x": 0,
            "position_y": 60000,
            "velocity_x": 0,
            "velocity_y": 0,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 300,
            "max_spawn_delay": 360,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "O-02",
            "mass": 5000,
            "position_x": 0,
            "position_y": -60000,
            "velocity_x": 0,
            "velocity_y": 0,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 300,
            "max_spawn_delay": 360,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "O-03",
            "mass": 5000,
            "position_x": 60000,
            "position_y": 0,
            "velocity_x": 0,
            "velocity_y": 0,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 300,
            "max_spawn_delay": 360,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "O-04",
            "mass": 5000,
            "position_x": -60000,
            "position_y": 0,
            "velocity_x": 0,
            "velocity_y": 0,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 300,
            "max_spawn_delay": 360,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        }
    ]
}