cShareSystems.load_pas("Lilly", [
    "coui://systems/lilly_all8.pas",           
    "coui://systems/lilly_debw.pas",           
    "coui://systems/lilly_erbw.pas",           
    "coui://systems/lilly_ersp.pas",           
    "coui://systems/lilly_ersw4.pas",          
    "coui://systems/lilly_ersw8.pas",          
    "coui://systems/lilly_icsw.pas",           
    "coui://systems/lilly_icwb c.pas",         
    "coui://systems/lilly_mnbw.pas",           
    "coui://systems/lilly_mt-sp2.pas",         
    "coui://systems/lilly_mt_sp.pas",          
    "coui://systems/lilly_mtbw.pas",           
    "coui://systems/lilly_trbw v2.pas",        
    "coui://systems/lilly_trbw.pas",           
    "coui://systems/lilly_eds12.pas",           
    "coui://systems/gamma_system.pas",           
    "coui://systems/gamma_system1.pas",           
    "coui://systems/gamma_system3.pas",           
    "coui://systems/gamma_system2.pas",           
    "coui://systems/gamma_system d2.pas",           
    "coui://systems/gamma_system l.pas",           
    "coui://systems/gamma_system l8.pas",           
    "coui://systems/gamma_system 20.pas",           
    "coui://systems/gamma_system 2g8d.pas",           
    "coui://systems/gamma_system 2g2b.pas",           
    "coui://systems/gamma_system 20m.pas",           
    "coui://systems/gamma_system 20-1.pas",           
    "coui://systems/gamma_system 14-4.pas",           
    "coui://systems/gamma_system d1b1.pas",           
    "coui://systems/gamma_system d1m4.pas",           
]);